# Generated by Django 3.1.4 on 2021-01-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('tag', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('slug', models.CharField(max_length=250)),
                ('timestamp', models.TimeField(auto_now=True)),
            ],
        ),
    ]
