# Generated by Django 3.1.4 on 2021-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
